### ISSUE TITLE
remaining niggles with container support

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/radiopadre#8]
If the user does not have sudo privileges to install the apt-get packages then radio-padre will not work. We need to add Docker/Singularity support, then we can launch radiopadre from a container.

### TODO:
- [ ] Add a Dockerfile to the repo  
- [ ] Sync Dockerfile to dockerhub 
- [ ] Add container support to run file: pull image from dockerhub if the user requests container support
